buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
        classpath 'org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.20'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

repositories {
    google()
    mavenCentral()
}

android {
    namespace 'com.github.nekit'
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        consumerProguardFiles 'consumer-rules.pro'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }
    
    sourceSets {
        main {
            java.srcDirs 'src_kt'
        }
    }
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib:1.9.20'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    implementation 'org.slf4j:slf4j-android:1.7.36'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.5'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.5'
    implementation 'com.fasterxml.jackson.module:jackson-module-kotlin:2.13.5'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.5'
    implementation 'org.bouncycastle:bcprov-jdk15on:1.70'
    implementation 'net.java.dev.jna:jna:5.13.0'
    implementation 'com.maxmind.geoip2:geoip2:4.0.1'
    
    // Netty for networking
    implementation 'io.netty:netty-all:4.1.100.Final'
    
    // Ktor for networking (alternative to Netty for Android compatibility)
    implementation 'io.ktor:ktor-network:2.3.7'
    implementation 'io.ktor:ktor-network-tls:2.3.7'
    
    // Android specific dependencies
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    
    // Test dependencies
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}